Update cs fixer
facile-it/sentry-psr-log pull request #2
Opened 2018-10-09 08:43 UTC by alexmanno

2018-10-09 09:15 UTC, Jean85 requested changes

2018-10-09 09:15 UTC, Jean85 commented on .php_cs.dist
> +return $config;
Missing new line at end of file.

2018-10-09 09:16 UTC, Jean85 commented
This creates a BC, because you're dumping PHP 7 as a supported version.

2018-10-09 09:34 UTC, alexmanno commented
> This creates a BC, because you're dumping PHP 7 as a supported version.

Can this create problems?

2018-10-09 09:39 UTC, Jean85 commented
Currently, it makes the build fail: https://travis-ci.org/facile-it/sentry-psr-log/builds/439046472

2018-10-10 10:35 UTC, thomasvargiu commented
Yes, it's a BC. I added this PR to v3.0 milestone

2018-10-11 11:03 UTC, thomasvargiu commented
Some improvementes

- [ ] `php_cs.dist` file should be added in `.gitattributes` ignored files.
- [ ] We should consider to use risky rules

2018-10-11 11:05 UTC, thomasvargiu commented
I just saw that proposed changes are in #3. Can we add this PR into #3?

2018-10-11 14:25 UTC, alexmanno commented
> I just saw that proposed changes are in #3. Can we add this PR into #3?

I think so!

2018-10-11 23:00 UTC, thomasvargiu commented
Closing. See #3

2018-10-11 23:00 UTC, closed without merging