Dump PHP 7.1
facile-it/sentry-psr-log pull request #3
Opened 2018-10-10 14:26 UTC by alexmanno

2018-10-11 11:15 UTC, thomasvargiu requested changes
Small changes... I think we should also add type hints where missing

2018-10-11 11:15 UTC, thomasvargiu commented on .travis.yml
> -        - EXECUTE_CS_CHECK=true
These checks should be added in php 7.1

2018-10-11 11:15 UTC, thomasvargiu commented on phpstan.neon
> +        - '#^Cannot cast object|string to string$#'
I think we shouldn't ignore this error. Where this error occurs?

2018-10-11 11:15 UTC, thomasvargiu commented on src/Logger.php
> +    /** @var Sender|SenderInterface */
We accept the interface in the constructor, so the implementation `Sender` should not be considered.

2018-10-11 11:15 UTC, thomasvargiu commented on src/Logger.php
> +    /** @var Sanitizer|SanitizerInterface */
We accept the interface in the constructor, so the implementation `Sanitizer` should not be considered.

2018-10-11 11:15 UTC, thomasvargiu commented on src/Logger.php
> +    /** @var Sender|SenderInterface */
Does phpstan throws errors?

2018-10-11 11:15 UTC, thomasvargiu commented on src/Logger.php
> +    /** @var Sanitizer|SanitizerInterface */
Does phpstan throws errors?

2018-10-11 14:22 UTC, alexmanno commented on phpstan.neon
> +        - '#^Cannot cast object|string to string$#'
src/Logger.php:96

2018-10-11 22:59 UTC, thomasvargiu requested changes

2018-10-11 22:59 UTC, thomasvargiu commented on composer.json
> +        "ci-phpstan": "phpstan analyse --no-progress -l7 src tests",
It's better to use current directory (`.`). Filters should be declared in phpstan configuration

2018-10-11 22:59 UTC, thomasvargiu commented on src/Logger.php
> +    public const DEBUG = 'debug';
These constants are useless. We can remove them.

2018-10-12 09:35 UTC, thomasvargiu commented on phpstan.neon
> +        - '#^Cannot cast object|string to string$#'
Could be a good idea to do the following?

```php
if (\is_object($message) && \method_exists($object, '__toString')) {
    $message = $message->__toString();
}
```

2018-10-13 13:31 UTC, thomasvargiu requested changes

2018-10-13 13:31 UTC, thomasvargiu commented on .travis.yml
> +    - php: 7.1
There are still 2 tests with the same environment (php 7.1) with `DEPS=locked`.
`EXECUTE_CS_CHECK=true` and `EXECUTE_TEST_SCRUTINIZER=true` should be added in the already existing enviroment.

2018-10-13 19:39 UTC, thomasvargiu approved these changes

2018-10-13 19:42 UTC, merged